### ISSUE TITLE
服务器端bug(GLA阶段-多线程？)

### ISSUE THREAD

**Issue by Pzoom522** [Pzoom522/MusiCoder#2]
#### 报错信息：
```
...
doing GLA..
Exception in thread Thread-[Num]:
Traceback (most recent call last):
  File "server.py", line 55, in receive_thread
    flag,filename,filesize =struct.unpack(self.packet,buf)
struct.error: unpack requires a bytes object of length 144

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 122, in receive_thread
    os.remove(task.endecoder.content_img_path)
UnboundLocalError: local variable 'task' referenced before assignment
...
```
#### 状态
- 尚不能稳定复现
- 尚未发现对服务体验有任何实质性影响
- 建议处理为warning

**Comment by Pzoom522** [comment]
- 问题定位
服务器端接收包部分 __错误处理__ 存在问题
